services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: passadmin
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: always

volumes:
  mongodb_data:
  mongodb_config:
